8 спринт. Добавление функционала в соответствие с ТЗ
Ekaterina-Firsova/java-kanban pull request #4
Opened 2024-05-24 11:03 UTC by Ekaterina-Firsova

2024-05-24 11:45 UTC, afomkina reviewed
- Нужно добавить библиотеку JUnit в проект. Предполагаю, что папка с библиотеками не добавилась в репозиторий, так в файле `.gitignore` прописано правило игнорирования файлов типа `*.jar`. Нужно ее удалить и закоммитить библиотеки в удаленный репозиторий 


-  Не хватает тестов в рамках тз:
```
Для расчёта статуса Epic. Граничные условия:
a. Все подзадачи со статусом NEW.
b. Все подзадачи со статусом DONE.
c. Подзадачи со статусами NEW и DONE.
d. Подзадачи со статусом IN_PROGRESS.

Для двух менеджеров задач InMemoryTaskManager и FileBackedTaskManager.
a. Чтобы избежать дублирования кода, нужен базовый класс с тестами на каждый метод из интерфейса abstract class TaskManagerTest<T extends TaskManager>.
b. Для подзадач нужно дополнительно проверить наличие эпика, а для эпика — расчёт статуса.
c. Добавить тест на корректность расчёта пересечения интервалов.

Для HistoryManager — тесты для всех методов интерфейса. Граничные условия:
a. Пустая история задач.
b. Дублирование.
c. Удаление из истории: начало, середина, конец.
```

2024-05-24 11:45 UTC, afomkina commented on src/Main.java
> +//        Task newTask2 = manager.addTask(task2, TaskStatus.IN_PROGRESS); //id 2
Лучше удалять код, а не комментировать его. Если он потребуется снова, всегда его можно восстановить из истории гита

2024-05-24 11:45 UTC, afomkina commented on src/Main.java
> +//        Subtask newSubTask3 = manager.addSubTask(subTask3, TaskStatus.NEW); //id 7
Удали, пожалуйста, весь закомментированный код

2024-05-24 11:45 UTC, afomkina commented on src/model/Task.java
> +     * Конструктор принимающий время и продолжительность задачи
Молодец, что пишешь java-doc 🔥

2024-05-24 11:45 UTC, afomkina commented on src/model/Task.java
> +        } catch (DateTimeParseException e) {
В коде не должно быть однобуквенных параметров, это делает код менее читаемым. Переименуй, пожалуйста

2024-05-24 11:45 UTC, afomkina commented on src/service/FileBackedTaskManager.java
> +//        manager.addTask(new Task("Покупка", "Купить молока","22-05-2024 09:01", 1 ), TaskStatus.IN_PROGRESS); //id 1
Закомментированный код нужно удалить

2024-05-24 11:45 UTC, afomkina commented on src/service/InMemoryTaskManager.java
> +    private final TreeSet<Task> tasksSet;
Отличный выбор коллекции 🔥

2024-05-24 11:45 UTC, afomkina commented on src/service/InMemoryTaskManager.java
>  import java.util.*;
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/ru/using-wildcard-imports-in-java/#:~:text=%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BE%D1%87%D0%BD%D1%8B%D1%85%20%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2%20%D0%BD%D0%B8%D0%BA%D0%B0%D0%BA%20%D0%BD%D0%B5,%D1%81%D1%82%D0%BE%D0%BB%D0%BA%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D1%81%20%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%BE%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82%D0%B0%20%D0%B8%D0%BC%D0%B5%D0%BD.) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2024-05-24 11:45 UTC, afomkina commented on src/service/InMemoryTaskManager.java
>      private ArrayList<Task> getSpecificTaskType(TaskType taskType) {
Метод должен возвращать интерфейс, а не определенную реализацию. Так программа станет более гибкой и не придется кастоваить List к ArrayList на 219 строке

2024-05-24 11:45 UTC, afomkina commented on src/service/InMemoryTaskManager.java
>      public ArrayList<Task> getEpicsSubtasks(Integer epicId) {
Метод должен возвращать интерфейс, а не конкретную реализацию

2024-05-24 11:45 UTC, afomkina commented on src/service/InMemoryTaskManager.java
>      private static Integer id;
Поле не должно быть статическим, для каждого менеджера задач, должен быть свой счетчик

2024-05-24 16:01 UTC, Ekaterina-Firsova commented on src/service/InMemoryTaskManager.java
> +    private final TreeSet<Task> tasksSet;
Спасибо)

2024-05-24 16:37 UTC, Ekaterina-Firsova commented on src/service/InMemoryTaskManager.java
>  import java.util.*;
Спасибо, настроила

2024-05-25 01:03 UTC, afomkina requested changes
Нужно добавить тест, который будет проверять корректность расчёта пересечения интервалов

2024-05-25 03:59 UTC, Ekaterina-Firsova commented on test/service/TaskManagerTest.java
> +        epic.setStatus(oldEpic.getStatus());
Да, что-то у меня уже мозг кипел, наверно)))

2024-05-25 04:01 UTC, Ekaterina-Firsova commented on test/service/FileExceptionHandlingTest.java
> +        FileBackedTaskManager manager = FileBackedTaskManager.loadFromFile(file);
Дело в том, что в моей программе не предусмотрено исключение, если  файл не найден. Я просто создаю новый. И у меня не получается спровоцировать исключение "Ошибка чтения файла"

2024-05-25 04:57 UTC, Ekaterina-Firsova commented on test/service/InMemoryTaskManagerTest.java
> +class InMemoryTaskManagerTest extends TaskManagerTest<TaskManager> {
В ТЗ написано "Чтобы избежать дублирования кода, нужен базовый класс с тестами на каждый метод из интерфейса abstract class TaskManagerTest<T extends TaskManager>." Я так и сделала. Те методы, которые уникальны для каждого из менеджеров остались в своих классах.

2024-05-25 05:28 UTC, Ekaterina-Firsova commented
у меня же тест на пересечение есть. InMemoryTaskManagerTest.should_return_6_after_add_Overlapping_Task(). Или я его не так сделала?

2024-05-26 13:21 UTC, afomkina commented on test/service/InMemoryTaskManagerTest.java
> +class InMemoryTaskManagerTest extends TaskManagerTest<TaskManager> {
А чем тогда метод task_with_same_id_should_be_equal уникален только для inmemory реализации?

2024-05-26 13:23 UTC, afomkina commented on test/service/InMemoryTaskManagerTest.java
> +class InMemoryTaskManagerTest extends TaskManagerTest<TaskManager> {
И для inmemory и для реализации с сохранением в файл две задачи с одинаковым id должны считаться одинаковыми

2024-05-26 13:25 UTC, afomkina commented on test/service/InMemoryTaskManagerTest.java
> +class InMemoryTaskManagerTest extends TaskManagerTest<TaskManager> {
Я считаю, что все тесты, которые у тебя реализованы в `InMemoryTaskManagerTest` подходят для обеих реализаций менеджера задач. Но я не буду настаивать на том, чтобы переносить их в общий тестовый класс

2024-05-26 13:37 UTC, afomkina requested changes
Прости, пожалуйста, что не заметила тест на пересечения. Оставила несколько комментариев

2024-05-26 13:37 UTC, afomkina commented on test/service/InMemoryTaskManagerTest.java
> +class InMemoryTaskManagerTest extends TaskManagerTest<TaskManager> {
Ниже оставлю комментарии по классу, которые нужно будет поправить, если ты не будешь выносить все тесты отсюда в абстрактный класс

2024-05-26 13:37 UTC, afomkina commented on test/service/InMemoryTaskManagerTest.java
>      TaskManager manager;
У поля всегда должен быть модификатор доступа

2024-05-26 13:37 UTC, afomkina commented on test/service/InMemoryTaskManagerTest.java
>          manager = new InMemoryTaskManager();
Используй метод createTaskManager для создания менеджера задач для данного теста

2024-05-26 13:37 UTC, afomkina commented on test/service/InMemoryTaskManagerTest.java
> +        HistoryManager historyManager = Managers.getDefaultHistory();
Этот объект не используется

2024-05-26 13:37 UTC, afomkina commented on test/service/FileExceptionHandlingTest.java
> +        FileBackedTaskManager manager = FileBackedTaskManager.loadFromFile(file);
Да, вижу, что ты в таком случае создаешь новый файл. Соответственно, тогда лучше проверить, что ошибки нет с помощью `assertDoesNotThrow`.
Получится что-то типо:

```
FileBackedTaskManager manager = assertDoesNotThrow(() -> FileBackedTaskManager.loadFromFile(file));

```

2024-05-26 13:39 UTC, afomkina commented on .idea/.gitignore
Нужно удалить все закоммиченные файлы из папки idea, в PR их быть не должно

2024-05-26 13:39 UTC, afomkina commented on lib/apiguardian-api-1.1.2.jar
Клево, что разобралась и добавила библиотеки 💪

2024-05-26 13:39 UTC, afomkina commented on test/service/InMemoryHistoryManagerTest.java
> +    HistoryManager historyManager;
У поля должен быть модификатор доступа

2024-05-26 15:23 UTC, Ekaterina-Firsova commented on test/service/InMemoryTaskManagerTest.java
> +class InMemoryTaskManagerTest extends TaskManagerTest<TaskManager> {
Да, я поняла что ты имеешь в виду. Действительно, эти тесты подойдут и для одного класса и для другого

2024-05-26 16:16 UTC, Ekaterina-Firsova commented on .idea/.gitignore
Я вроде все сделала чтоб они удалились. Мне кажется, пока ветки не смержу они не удалятся

2024-05-26 18:40 UTC, afomkina approved these changes

2024-05-26 18:45 UTC, merged